
all_configs = {
    "asterix": {
        "ANNEAL_LR": True,
        "SGD_LR": 0.52,
        "NUM_ENVS": 64,
        "NUM_STEPS": 128,
        "TOTAL_TIMESTEPS": 1e7,
        "UPDATE_EPOCHS": 4,
        "NUM_MINIBATCHES": 8,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ENV_NAME": "Asterix-MinAtar",
        "HSIZE": 64,
        "ACTIVATION": "relu",
        "DEBUG": False,
        "PPO_TEMP": 15.0353,
        "SGD_TEMP": 15.414,
        "CONTINUOUS": False,
        "LR": 3e-3,
        "B1": 0.9,
        "B2": 0.999,
        "RECUR_LR":3e-3
    },
    "freeway": {
        "NUM_ENVS": 64,
        "NUM_STEPS": 128,
        "TOTAL_TIMESTEPS": 1e7,
        "UPDATE_EPOCHS": 4,
        "NUM_MINIBATCHES": 8,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ENV_NAME": "Freeway-MinAtar",
        "HSIZE": 64,
        "ACTIVATION": "relu",
        "DEBUG": False,
        "PPO_TEMP": 61.8369,
        "SGD_TEMP": 61.6,
        "CONTINUOUS": False,
        "SGD_LR": 0.56,
        "LR": 1e-3,
        "B1": 0.9,
        "B2": 0.99,
        "ANNEAL_LR": True,
        "RECUR_LR":1e-3
    },
    "breakout": {
	    "NUM_ENVS": 64,
	    "SGD_LR": 1.017,
	    "ANNEAL_LR": True,
	    "NUM_STEPS": 128,
	    "TOTAL_TIMESTEPS": 1e7,
	    "UPDATE_EPOCHS": 4,
	    "NUM_MINIBATCHES": 8,
	    "GAMMA": 0.99,
	    "GAE_LAMBDA": 0.95,
	    "CLIP_EPS": 0.2,
	    "ENT_COEF": 0.01,
	    "VF_COEF": 0.5,
	    "MAX_GRAD_NORM": 0.5,
	    "ENV_NAME": "Breakout-MinAtar",
	    "HSIZE": 64,
	    "ACTIVATION": "relu",
	    "DEBUG": False,
	    "SGD_TEMP": 20.50,
	    "PPO_TEMP": 50.0822,
	    "CONTINUOUS": False,
	    "LR": 1e-2,
	    "B1": 0.9,
	    "B2": 0.99,
	    "RECUR_LR": 7e-3
	},
    "breakout_test": {
        "NUM_ENVS": 2,
        "SGD_LR": 1.017,
        "ANNEAL_LR": True,
        "NUM_STEPS": 16,
        "TOTAL_TIMESTEPS": 32,
        "UPDATE_EPOCHS": 1,
        "NUM_MINIBATCHES": 1,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ENV_NAME": "Breakout-MinAtar",
        "HSIZE": 8,
        "ACTIVATION": "relu",
        "DEBUG": False,
        "SGD_TEMP": 20.50,
        "PPO_TEMP": 50.0822,
        "CONTINUOUS": False,
        "LR": 1e-2,
        "B1": 0.9,
        "B2": 0.99,
        "RECUR_LR": 7e-3
    },
    "spaceinvaders": {
        "NUM_ENVS": 64,
        "NUM_STEPS": 128,
        "TOTAL_TIMESTEPS": 1e7,
        "UPDATE_EPOCHS": 4,
        "NUM_MINIBATCHES": 8,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ENV_NAME": "SpaceInvaders-MinAtar",
        "HSIZE": 64,
        "ACTIVATION": "relu",
        "DEBUG": False,
        "PPO_TEMP": 167.0913,
        "CONTINUOUS": False,
        "SGD_TEMP": 146.20,
        "SGD_LR": 1.17,
        "LR": 7e-3,
        "B1": 0.9,
        "B2": 0.99,
        "ANNEAL_LR": True,
        "RECUR_LR":3e-3

    },
    "ant": {
        "NUM_ENVS": 2048,
        "NUM_STEPS": 10,
        "TOTAL_TIMESTEPS": 3e7,
        "UPDATE_EPOCHS": 4,
        "NUM_MINIBATCHES": 32,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.0,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ACTIVATION": "tanh",
        "HSIZE": 64,
        "ENV_NAME": "Brax-ant",
        "BACKEND": "positional",
        "SYMLOG_OBS": False,
        "CLIP_ACTION": True,
        "DEBUG": False,
        "NORMALIZE": True,
        "CONTINUOUS": True,
        "PPO_TEMP": 6517.31,
        "SGD_TEMP": 4443.31,
        "SGD_LR": 0.17,
        "LR": 3e-4,
        "B1": 0.99,
        "B2": 0.99,
        "ANNEAL_LR": True,
        "RECUR_LR": 3e-4
    },
    "gridworld": {
        "SGD_LR": 1.33,
        "ANNEAL_LR": True,
        "NUM_ENVS": 1024,
        "NUM_STEPS": 20,
        "TOTAL_TIMESTEPS": 5e6,
        "UPDATE_EPOCHS": 2,
        "NUM_MINIBATCHES": 16,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ACTIVATION": "tanh",
        "HSIZE": 16,
        "ENV_NAME": "gridworld",
        "SGD_TEMP": 1.0,
        "DEBUG": False,
        "PPO_TEMP": 1.0,
        "CONTINUOUS": False,
        "LR": 1e-4,
        "B1": 0.99,
        "B2": 0.99,
    },
    "cartpole": {
        "SGD_LR": 2.5e-4,
        "ANNEAL_LR": True,
        "NUM_ENVS": 4,
        "NUM_STEPS": 128,
        "TOTAL_TIMESTEPS": 5e5,
        "UPDATE_EPOCHS": 4,
        "NUM_MINIBATCHES": 4,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ACTIVATION": "tanh",
        "HSIZE": 64,
        "ENV_NAME": "CartPole-v1",
        "DEBUG": False,
        "PPO_TEMP": 475,  # From openAI Gym reward threshold
        "CONTINUOUS": False,
        "LR": 1e-3,
        "SGD_TEMP": 500,
        "B1":0.9,
        "B2":0.999,
                "RECUR_LR":1e-3

    },
    "humanoid": {
        "ANNEAL_LR": True,
        "NUM_ENVS": 2048,
        "NUM_STEPS": 10,
        "TOTAL_TIMESTEPS": 3e7,
        "UPDATE_EPOCHS": 4,
        "NUM_MINIBATCHES": 32,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.0,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ACTIVATION": "tanh",
        "HSIZE": 64,
        "ENV_NAME": "Brax-humanoid",
        "BACKEND": "positional",
        "SYMLOG_OBS": False,
        "CLIP_ACTION": True,
        "DEBUG": False,
        "NORMALIZE": True,
        "CONTINUOUS": True,
        "PPO_TEMP": 6517.31,
        "LR": 3e-4,
        "SGD_LR": 0.053,
        "SGD_TEMP": 1,        
        "B1":0.9,
        "B2":0.999,
                "RECUR_LR":3e-4

    },
    "walker": {
        "ANNEAL_LR": True,
        "NUM_ENVS": 2048,
        "NUM_STEPS": 10,
        "TOTAL_TIMESTEPS": 3e7,
        "UPDATE_EPOCHS": 4,
        "NUM_MINIBATCHES": 32,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.0,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ACTIVATION": "tanh",
        "HSIZE": 64,
        "ENV_NAME": "Brax-walker2d",
        "BACKEND": "positional",
        "SYMLOG_OBS": False,
        "CLIP_ACTION": True,
        "DEBUG": False,
        "NORMALIZE": True,
        "CONTINUOUS": True,
        "PPO_TEMP": 6517.31,
        "LR": 1e-3,
        "SGD_LR": 0.52,
        "SGD_TEMP": 1,        
        "B1":0.9,
        "B2":0.999,
                "RECUR_LR":1e-3

    },
    "hopper": {
        "ANNEAL_LR": True,
        "NUM_ENVS": 2048,
        "NUM_STEPS": 10,
        "TOTAL_TIMESTEPS": 3e7,
        "UPDATE_EPOCHS": 4,
        "NUM_MINIBATCHES": 32,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "ENT_COEF": 0.0,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 0.5,
        "ACTIVATION": "tanh",
        "HSIZE": 64,
        "ENV_NAME": "Brax-hopper",
        "BACKEND": "positional",
        "SYMLOG_OBS": False,
        "CLIP_ACTION": True,
        "DEBUG": False,
        "NORMALIZE": True,
        "CONTINUOUS": True,
        "PPO_TEMP": 6517.31,
        "LR": 8e-4,
        "SGD_LR": 0.27,
        "SGD_TEMP": 1,        "B1":0.9,
        "B2":0.999,
                "RECUR_LR":8e-4

    },

}
